name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'
      - name: node check
        run: |
          npm ci
          npm run test:ci
        env:
          CI: true

  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browsers:
          - chrome
          - firefox
          - edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: 'test/component/cypress.config.ts'
          start: npm run vue:component:serve
          browser: ${{ matrix.browsers }}

  status-checks:
    name: status-checks
    needs:
      - build
      - cypress
    permissions:
      contents: none
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Validation Status checks
        run: |
          echo 'Configuration for Status checks that are required'
          echo '${{ toJSON(needs) }}'
          if [[ (('skipped' == '${{ needs.build.result }}') || ('success' == '${{ needs.build.result }}')) && (('skipped' == '${{ needs.cypress.result }}') || ('success' == '${{ needs.cypress.result }}')) ]]; then
            exit 0
          fi
          exit 1
